/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodtestschedule;

/**
 *
 * @author Arisha Mirza
 * 16/03/2025
 * BloodTestSchedulerGUI.java Ver 1.0
 */
public class BloodTestSchedulerGUI extends javax.swing.JFrame {
    private Scheduler scheduler;
    private AbsenceTracker absenceTracker;

    /**
     * Creates new form BloodTestSchedulerGUI
     */
    public BloodTestSchedulerGUI() {
        scheduler = new Scheduler();
        absenceTracker = new AbsenceTracker();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        priorityLabel = new javax.swing.JLabel();
        gpLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        fromHospitalLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        displayButton = new javax.swing.JButton();
        viewNextButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayAreaText = new javax.swing.JTextArea();
        fromHospitalCheckbox = new javax.swing.JCheckBox();
        nameTextField = new javax.swing.JTextField();
        gpTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        priorityComboBox = new javax.swing.JComboBox<>();
        displayAbsencesButton = new javax.swing.JButton();
        addAbsenceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        headerLabel.setText("Blood Test Schedule Manager");

        nameLabel.setText("Name");

        priorityLabel.setText("Priority");

        gpLabel.setText("GP Details");

        ageLabel.setText("Age");

        fromHospitalLabel.setText("From Hospital");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        viewNextButton.setText("View Priority Patient");
        viewNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNextButtonActionPerformed(evt);
            }
        });

        displayAreaText.setColumns(20);
        displayAreaText.setRows(5);
        jScrollPane1.setViewportView(displayAreaText);

        fromHospitalCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromHospitalCheckboxActionPerformed(evt);
            }
        });

        priorityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "Urgent", " " }));

        displayAbsencesButton.setText("View Absences");
        displayAbsencesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAbsencesButtonActionPerformed(evt);
            }
        });

        addAbsenceButton.setText("Add to Absence List");
        addAbsenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAbsenceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(headerLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gpLabel)
                                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priorityLabel))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(fromHospitalLabel)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fromHospitalCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField)
                            .addComponent(gpTextField)
                            .addComponent(ageTextField)
                            .addComponent(priorityComboBox, 0, 172, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addAbsenceButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addGap(18, 18, 18)
                                .addComponent(displayButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewNextButton)
                                .addGap(18, 18, 18)
                                .addComponent(displayAbsencesButton)))))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(headerLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priorityLabel)
                            .addComponent(priorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gpLabel)
                                    .addComponent(gpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ageLabel))
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(fromHospitalCheckbox))
                    .addComponent(fromHospitalLabel))
                .addGap(19, 19, 19)
                .addComponent(addAbsenceButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(displayButton)
                    .addComponent(viewNextButton)
                    .addComponent(displayAbsencesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // get and store Patient Details
        String name = nameTextField.getText().trim();
        String gpDetails = gpTextField.getText().trim();
        String priority = (String) priorityComboBox.getSelectedItem();
        String ageStr = ageTextField.getText().trim();
        int age = 0;
        
        //try catch block for error handling
        try {age = Integer.parseInt(ageStr);
            } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid age.");
           return;
            }
        
        boolean fromHospital = fromHospitalCheckbox.isSelected();

        // create a new BloodTestManager object
        BloodTestSchedule patient = new BloodTestManager(name, priority, gpDetails, age, fromHospital);
    
        // Add the patient to the Scheduler
        scheduler.addRequest(patient);
    
        // clear fields after adding
        nameTextField.setText("");
        gpTextField.setText("");
        ageTextField.setText("");
        fromHospitalCheckbox.setSelected(false);
    
        javax.swing.JOptionPane.showMessageDialog(this, "Patient added successfully!");

    }//GEN-LAST:event_addButtonActionPerformed

    private void fromHospitalCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromHospitalCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromHospitalCheckboxActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
       //build string for all patients in scheduler to display
        BloodTestSchedule[] patients = scheduler.getAllRequests();
        StringBuilder sb = new StringBuilder();
        for (BloodTestSchedule patient : patients) {
            sb.append(patient.toString()).append("\n");
        }
        displayAreaText.setText(sb.toString());
    }//GEN-LAST:event_displayButtonActionPerformed

    private void viewNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNextButtonActionPerformed
        // view priority patients
                                        
        BloodTestSchedule nextPatient = scheduler.getNextPerson();
            if (nextPatient != null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Next patient:\n" + nextPatient.toString());
            } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No patients in the queue.");
        }
    }//GEN-LAST:event_viewNextButtonActionPerformed

    private void displayAbsencesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAbsencesButtonActionPerformed
        // TODO add your handling code here:                                                                                             
    // get the absence list from the absence tracker
    BloodTestSchedule[] absences = absenceTracker.getAbsences();
        StringBuilder sb = new StringBuilder();
        if(absences.length == 0) {
            sb.append("No patients on absence list.");
        } else {
            sb.append("Absence List:\n");
            for(BloodTestSchedule patient : absences) {
                sb.append(patient.toString()).append("\n");
            }
        }
        javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), "Absence List", javax.swing.JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_displayAbsencesButtonActionPerformed

    private void addAbsenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAbsenceButtonActionPerformed
        // removes patient from scheduler to add to absence tracker
        BloodTestSchedule noShowPatient = scheduler.processNextPerson();
    if(noShowPatient != null) {
            // Add patient to absence tracker
            absenceTracker.addAbsence(noShowPatient);
            javax.swing.JOptionPane.showMessageDialog(this, "Patient has been marked absent.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No patient has been marked as absent.");
        }       
    }//GEN-LAST:event_addAbsenceButtonActionPerformed
        /**    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodTestSchedulerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAbsenceButton;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton displayAbsencesButton;
    private javax.swing.JTextArea displayAreaText;
    private javax.swing.JButton displayButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JCheckBox fromHospitalCheckbox;
    private javax.swing.JLabel fromHospitalLabel;
    private javax.swing.JLabel gpLabel;
    private javax.swing.JTextField gpTextField;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox<String> priorityComboBox;
    private javax.swing.JLabel priorityLabel;
    private javax.swing.JButton viewNextButton;
    // End of variables declaration//GEN-END:variables
}
